CREATE TABLE [dbo].[File835](
	[FileId] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [varchar](200) NOT NULL,
	[SenderIdQualifier] [varchar](50) NULL,
	[SenderId] [varchar](50) NULL,
	[ReceiverIdQualifier] [varchar](50) NULL,
	[ReceiverId] [varchar](50) NULL,
	[InterchangeControlNumber] [varchar](50) NULL,
	[ProductionFlag] [varchar](50) NULL,
	[TransactionDate] [varchar](50) NULL,
	[TransactionTime] [varchar](50) NULL,
	[MoneytaryAmount] [varchar](50) NULL,
	[CreditFlag] [varchar](50) NULL,
	[PaymentMethodCode] [varchar](50) NULL,
	[PaymentFormatCode] [varchar](50) NULL,
	[Sender_Dfi_Id_Qualifier] [varchar](50) NULL,
	[Sender_Dfi_Id] [varchar](50) NULL,
	[SenderAccountQualifier] [varchar](50) NULL,
	[SenderAccountNumber] [varchar](50) NULL,
	[OriginatingCompanyId] [varchar](50) NULL,
	[OriginatingCompanySupplementalCode] [varchar](50) NULL,
	[Receiver_Dfi_Id_Qualifier] [varchar](50) NULL,
	[ReceiverBankId] [varchar](50) NULL,
	[ReceiverAccountQualifier] [varchar](50) NULL,
	[ReceiverAccountNumber] [varchar](50) NULL,
	[CheckIssueDate] [varchar](50) NULL,
	[TraceTypeCode] [varchar](50) NULL,
	[ReferenceId] [varchar](50) NULL,
	[OriginatingComapnySupplementalCode] [varchar](50) NULL,
	[ReceiverReferenceId] [varchar](50) NULL,
	[PayerIdCode] [varchar](50) NULL,
	[PayerName] [varchar](200) NULL,
	[PayerIdQualifier] [varchar](50) NULL,
	[PayerId] [varchar](50) NULL,
	[PayerAddress] [varchar](200) NULL,
	[PayerAddress2] [varchar](50) NULL,
	[PayerCity] [varchar](50) NULL,
	[PayerState] [varchar](50) NULL,
	[PayerZip] [varchar](50) NULL,
	[ContactFunctionCode] [varchar](50) NULL,
	[ContactName] [varchar](200) NULL,
	[ContactCommunicationQualifier] [varchar](50) NULL,
	[ContactCommunicationNumber] [varchar](50) NULL,
	[TechFunctionCode] [varchar](50) NULL,
	[TechName] [varchar](200) NULL,
	[TechCommunicationQualifier1] [varchar](50) NULL,
	[TechCommunicationNumber1] [varchar](50) NULL,
	[TechCommunicationQualifier2] [varchar](50) NULL,
	[TechCommunicationNumber2] [varchar](50) NULL,
	[WebFunctionCode] [varchar](50) NULL,
	[WebName] [varchar](50) NULL,
	[WebCommunicationQualifier] [varchar](50) NULL,
	[WebCommunicationNumber] [varchar](200) NULL,
	[PayeeIdCode] [varchar](50) NULL,
	[PayeeName] [varchar](200) NULL,
	[PayeeIdQualifier] [varchar](50) NULL,
	[PayeeId] [varchar](50) NULL,
	[PayeeAddress] [varchar](200) NULL,
	[PayeeAddress2] [varchar](50) NULL,
	[PayeeCity] [varchar](50) NULL,
	[PayeeState] [varchar](50) NULL,
	[PayeeZip] [varchar](50) NULL,
	[PayeeAdditionalIdQualifier] [varchar](50) NULL,
	[PayeeAdditionalId] [varchar](50) NULL,
	[PayeeAdditionalIdQualifier2] [varchar](50) NULL,
	[PayeeAdditionalId2] [varchar](50) NULL,
	[ProviderAdjustmentId] [varchar](50) NULL,
	[ProviderFiscalDate] [varchar](50) NULL,
	[ProviderAdjustmentReasonCode] [varchar](50) NULL,
	[ProviderAdjustmentId1] [varchar](50) NULL,
	[ProviderAdjustmentAmount1] [varchar](50) NULL,
	[ProviderAdjustmentId2] [varchar](50) NULL,
	[ProviderAdjustmentAmount2] [varchar](50) NULL,
	[ProviderAdjustmentId3] [varchar](50) NULL,
	[ProviderAdjustmentAmount3] [varchar](50) NULL,
	[ProviderAdjustmentId4] [varchar](50) NULL,
	[ProviderAdjustmentAmount4] [varchar](50) NULL,
	[ProviderAdjustmentId5] [varchar](50) NULL,
	[ProviderAdjustmentAmount5] [varchar](50) NULL,
	[ProviderAdjustmentId6] [varchar](50) NULL,
	[ProviderAdjustmentAmount6] [varchar](50) NULL,
	[CreateUser] [varchar](50) NOT NULL,
	[CreateDate] [varchar](50) NOT NULL,
 CONSTRAINT [PK_File835] PRIMARY KEY CLUSTERED 
(
	[FileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Claim835](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileId] [int] NOT NULL,
	[PatientControlNumber] [varchar](50) NULL,
	[ClaimStatus] [varchar](50) NULL,
	[TotalChargeAmount] [varchar](50) NULL,
	[TotalPaidAmount] [varchar](50) NULL,
	[PatientResponsibilityAmount] [varchar](50) NULL,
	[ClaimFilingIndicator] [varchar](50) NULL,
	[PayerClaimcCntrolNumber] [varchar](50) NULL,
	[FacilityTypeCode] [varchar](50) NULL,
	[ClaimFrequencyCode] [varchar](50) NULL,
	[PatientStatusCode] [varchar](50) NULL,
	[DrgCode] [varchar](50) NULL,
	[DrgWeight] [varchar](50) NULL,
	[DischargePercent] [varchar](50) NULL,
	[ClaimAdjustmentGroupCode] [varchar](50) NULL,
	[AdjustmentReasoncCode1] [varchar](50) NULL,
	[AdjustmentAmount1] [varchar](50) NULL,
	[AdjustmentQuantity1] [varchar](50) NULL,
	[AdjustmentReasonCode2] [varchar](50) NULL,
	[AdjustmentAmount2] [varchar](50) NULL,
	[AdjustmentQuantity2] [varchar](50) NULL,
	[AdjustmentReasonCode3] [varchar](50) NULL,
	[AdjustmentAmount3] [varchar](50) NULL,
	[AdjustmentQuantity3] [varchar](50) NULL,
	[AdjustmentReasonCode4] [varchar](50) NULL,
	[AdjustmentAmount4] [varchar](50) NULL,
	[AdjustmentQuantity4] [varchar](50) NULL,
	[AdjustmentReasonCode5] [varchar](50) NULL,
	[AdjustmentAmount5] [varchar](50) NULL,
	[AdjustmentQuantity5] [varchar](50) NULL,
	[AdjustmentReasonCode6] [varchar](50) NULL,
	[AdjustmentAmount6] [varchar](50) NULL,
	[AdjustmentQuantity6] [varchar](50) NULL,
	[PatientCode] [varchar](50) NULL,
	[PatientEntityType] [varchar](50) NULL,
	[PatientLastName] [varchar](50) NULL,
	[PatientFirstName] [varchar](50) NULL,
	[PatientMiddleInitial] [varchar](50) NULL,
	[PatientPrefix] [varchar](50) NULL,
	[PatientSuffix] [varchar](50) NULL,
	[PatientIdQualifier] [varchar](50) NULL,
	[PatientId] [varchar](50) NULL,
	[ProviderCode] [varchar](50) NULL,
	[ProviderEntityType] [varchar](50) NULL,
	[ProviderLastName] [varchar](50) NULL,
	[ProviderFirstName] [varchar](50) NULL,
	[ProviderMiddleInitial] [varchar](50) NULL,
	[ProviderPrefix] [varchar](50) NULL,
	[ProviderSuffix] [varchar](50) NULL,
	[ProviderIdQualifier] [varchar](50) NULL,
	[ProviderId] [varchar](50) NULL,
	[ExpirationDate] [varchar](50) NULL,
	[ClaimReceivedDate] [varchar](50) NULL,
	[SupplementalAmountQualifier] [varchar](50) NULL,
	[SupplementalAmount] [varchar](50) NULL,
	[ServiceTypeCode] [varchar](50) NULL,
	[ProcedureCode] [varchar](50) NULL,
	[Modifier1] [varchar](50) NULL,
	[Modifier2] [varchar](50) NULL,
	[Modifier3] [varchar](50) NULL,
	[Modifier4] [varchar](50) NULL,
	[ProcedureDescription] [varchar](200) NULL,
	[LineChargeAmount] [varchar](50) NULL,
	[LinePaidAmount] [varchar](50) NULL,
	[RevenueCode] [varchar](50) NULL,
	[PaidUnitCount] [varchar](50) NULL,
	[DiffServiceTypeCode] [varchar](50) NULL,
	[DiffProcedureCode] [varchar](50) NULL,
	[DiffModifier1] [varchar](50) NULL,
	[DiffModifier2] [varchar](50) NULL,
	[DiffModifier3] [varchar](50) NULL,
	[DiffModifier4] [varchar](50) NULL,
	[DiffProcedureDescription] [varchar](200) NULL,
	[ChargeUnitCount] [varchar](50) NULL,
	[ServiceStartDate] [varchar](50) NULL,
	[ServiceEndDate] [varchar](50) NULL,
	[ServiceDate] [varchar](50) NULL,
	[LineAdjustmentGroupCode] [varchar](50) NULL,
	[LineAdjustmentReasonCode1] [varchar](50) NULL,
	[LineAdjustmentAmount1] [varchar](50) NULL,
	[LineAdjustmentQuantity1] [varchar](50) NULL,
	[LineAdjustmentReasonCode2] [varchar](50) NULL,
	[LineAdjustmentAmount2] [varchar](50) NULL,
	[LineAdjustmentQuantity2] [varchar](50) NULL,
	[LineAdjustmentReasonCode3] [varchar](50) NULL,
	[LineAdjustmentAmount3] [varchar](50) NULL,
	[LineAdjustmentQuantity3] [varchar](50) NULL,
	[LineAdjustmentReasonCode4] [varchar](50) NULL,
	[LineAdjustmentAmount4] [varchar](50) NULL,
	[LineAdjustmentQuantity4] [varchar](50) NULL,
	[LineAdjustmentReasonCode5] [varchar](50) NULL,
	[LineAdjustmentAmount5] [varchar](50) NULL,
	[LineAdjustmentQuantity5] [varchar](50) NULL,
	[LineAdjustmentReasonCode6] [varchar](50) NULL,
	[LineAdjustmentAmount6] [varchar](50) NULL,
	[LineAdjustmentQuantity6] [varchar](50) NULL,
	[ProviderReferenceNumber] [varchar](50) NULL,
	[LineItemControlNumber] [varchar](50) NULL,
	[RenderingProviderNpi] [varchar](50) NULL,
	[RenderingProviderTaxId] [varchar](50) NULL,
	[LineAllowedAmount] [varchar](50) NULL,
	[RemarkCode] [varchar](50) NULL,
 CONSTRAINT [PK_Claim835] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


