using EncDataModel.NCPDP42;
using ExportNCPDP.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExportNCPDP.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ExportNCPDPController : ControllerBase
    {
        private readonly ILogger<ExportNCPDPController> _logger;
        private readonly NCPDPContext _context;
        public ExportNCPDPController(ILogger<ExportNCPDPController> logger, NCPDPContext context)
        {
            _logger = logger;
            _context = context;
        }
        //ExportNCPDP
        [HttpGet]
        public List<string> GetNCPDPCountsForExport()
        {
            List<string> result = new List<string>();
            _logger.Log(LogLevel.Information, "query total counts for NCPDP export");
            IConfigurationRoot configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            string DestinationFolder = configuration["NCPDPDestinationFolder"];
            int TotalRecords = _context.Details.Count();
            result.Add(TotalRecords.ToString());
            result.Add(DestinationFolder);
            return result;
        }
        //ExportNCPDP/1
        [HttpGet("{id}")]
        public List<string> ExportNCPDPFiles(long id)
        {
            List<string> result = new List<string>();
            _logger.Log(LogLevel.Information, "Generate NCPDP Files");
            IConfigurationRoot configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
            string DestinationFolder = configuration["NCPDPDestinationFolder"];
            int goodDatabaseRecords = 0;
            string ProductionFlag = "P";
            if (id != 1) ProductionFlag = "T";
            StringBuilder sb = new StringBuilder();
            int sequenceNumber = 1;
            foreach (HisHeader header in _context.Headers.Where(x=>x.CountyCode=="305"))
            {
                sb.Clear();
                sb.AppendLine(Pah42Header(header, ProductionFlag));
                foreach (HisDetail detail in _context.Details.Where(x => x.FileID == header.FileID)) 
                {
                    sb.AppendLine(Pah42Detail(detail));
                    foreach (HisCompound1 cd1 in _context.Compound1s.Where(x => x.DetailID == detail.DetailID)) 
                    {
                        sb.AppendLine(Pah42Cd1(cd1));
                    }
                    foreach (HisCompound2 cd2 in _context.Compound2s.Where(x => x.DetailID == detail.DetailID)) 
                    {
                        sb.AppendLine(Pah42Cd2(cd2));
                    }
                    goodDatabaseRecords++;
                }
                sb.AppendLine(Pah42Trailer(header));
                System.IO.File.WriteAllText(Path.Combine(DestinationFolder, "IEHP_" + header.CountyCode + "_P42_MCE_" + DateTime.Today.ToString("yyyyMMdd") + "_" + sequenceNumber.ToString().PadLeft(5,'0') + ".dat"), sb.ToString());
                sequenceNumber++;
            }
            sequenceNumber = 1;
            foreach (HisHeader header in _context.Headers.Where(x => x.CountyCode == "306"))
            {
                sb.Clear();
                sb.AppendLine(Pah42Header(header, ProductionFlag));
                foreach (HisDetail detail in _context.Details.Where(x => x.FileID == header.FileID))
                {
                    sb.AppendLine(Pah42Detail(detail));
                    foreach (HisCompound1 cd1 in _context.Compound1s.Where(x => x.DetailID == detail.DetailID))
                    {
                        sb.AppendLine(Pah42Cd1(cd1));
                    }
                    foreach (HisCompound2 cd2 in _context.Compound2s.Where(x => x.DetailID == detail.DetailID))
                    {
                        sb.AppendLine(Pah42Cd2(cd2));
                    }
                    goodDatabaseRecords++;
                }
                sb.AppendLine(Pah42Trailer(header));
                System.IO.File.WriteAllText(Path.Combine(DestinationFolder, "IEHP_" + header.CountyCode + "_P42_MCE_" + DateTime.Today.ToString("yyyyMMdd") + "_" + sequenceNumber.ToString().PadLeft(5, '0') + ".dat"), sb.ToString());
                sequenceNumber++;
            }

            result.Add(_context.Details.Count().ToString());
            result.Add(goodDatabaseRecords.ToString());
            return result;
        }
        private string Pah42Header(HisHeader header, string ProductionFlag) 
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(header.RecordType.PadRight(2,' '));
            sb.Append(header.VersionReleaseNumber.PadRight(2,' '));
            sb.Append(header.SenderID.PadRight(24, ' '));
            sb.Append(header.BatchNumber.PadRight(7,' '));
            sb.Append(header.CreationDate);
            sb.Append(header.CreationTime);
            sb.Append(header.ReceiverID.PadRight(24, ' '));
            sb.Append(header.ReportStartDate);
            sb.Append(header.ReportEndDate);
            sb.Append(ProductionFlag);
            sb.Append(header.TransmissionAction);
            sb.Append(header.SubmissionNumber);
            sb.Append("".PadRight(3609, ' '));
            return sb.ToString();
        }
        private string Pah42Trailer(HisHeader header) 
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("PT");
            sb.Append(header.Total_Record_Count);
            sb.Append(header.Total_Net_Amount_Due);
            sb.Append(header.Total_Gross_Amount_Due);
            sb.Append(header.Total_Patient_Pay_Amount);
            sb.Append("".PadRight(3652, ' '));
            return sb.ToString();
        }
        private string Pah42Detail(HisDetail detail) 
        {
            StringBuilder sb = new StringBuilder();
            sb.Append((detail.Record_Type ?? "").PadRight(2, ' '));
            sb.Append((detail.Record_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Eligible_Coverage_Code ?? "").PadRight(3, ' '));
            sb.Append((detail.User_Benefit_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.User_Coverage_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.Eligibility_Group_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Line_Of_Business_Code ?? "").PadRight(6, ' '));
            sb.Append((detail.Insurance_Code ?? "").PadRight(20, ' '));
            sb.Append((detail.Client_Assigned_Location_Code ?? "").PadRight(20, ' '));
            sb.Append((detail.Client_Pass_Through ?? "").PadRight(200, ' '));
            sb.Append((detail.Card_Holder_ID ?? "").PadRight(20, ' '));
            sb.Append((detail.CH_Last_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.CH_First_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.CH_Middle_Initial ?? "").PadRight(1, ' '));
            sb.Append((detail.CH_Name_Suffix ?? "").PadRight(10, ' '));
            sb.Append((detail.CH_Address_Line_1 ?? "").PadRight(40, ' '));
            sb.Append((detail.CH_Address_Line_2 ?? "").PadRight(40, ' '));
            sb.Append((detail.CH_City ?? "").PadRight(30, ' '));
            sb.Append((detail.CH_State ?? "").PadRight(2, ' '));
            sb.Append((detail.CH_Zip ?? "").PadRight(15, ' '));
            sb.Append((detail.CH_Entity_Country_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.CH_Date_Of_Birth ?? "").PadRight(8, ' '));
            sb.Append((detail.CH_Gender_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.CH_Medicare_Plan_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.CH_Payroll_Class ?? "").PadRight(1, ' '));
            sb.Append((detail.Patient_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.Patient_ID ?? "").PadRight(20, ' '));
            sb.Append((detail.PT_Last_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.PT_First_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.PT_Middle_Initial ?? "").PadRight(1, ' '));
            sb.Append((detail.PT_Name_Suffix ?? "").PadRight(10, ' '));
            sb.Append((detail.PT_Address_Line_1 ?? "").PadRight(40, ' '));
            sb.Append((detail.PT_Address_Line_2 ?? "").PadRight(40, ' '));
            sb.Append((detail.PT_City ?? "").PadRight(30, ' '));
            sb.Append((detail.PT_State ?? "").PadRight(2, ' '));
            sb.Append((detail.PT_Zip ?? "").PadRight(15, ' '));
            sb.Append((detail.PT_Country_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.PT_Date_Of_Birth ?? "").PadRight(8, ' '));
            sb.Append((detail.PT_Gender_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Eligibility_Relationship_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.PT_Age ?? "").PadRight(3, ' '));
            sb.Append((detail.PT_Person_Code ?? "").PadRight(3, ' '));
            sb.Append((detail.Patient_Relationship_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Eligibility_Clarification_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Facility_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.Group_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Carrier_Number ?? "").PadRight(9, ' '));
            sb.Append((detail.Benefit_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Contract_Number ?? "").PadRight(8, ' '));
            sb.Append((detail.Benefit_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.Member_Submitted_Claim_Program_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.NonPos_Claim_Override_Code1 ?? "").PadRight(1, ' '));
            sb.Append((detail.NonPos_Claim_Override_Code2 ?? "").PadRight(1, ' '));
            sb.Append((detail.NonPos_Claim_Override_Code3 ?? "").PadRight(1, ' '));
            sb.Append((detail.Copay_Modifier_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Preferred_Alternative_File_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Coverage_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.Plan_Benefit_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.Plan_Type ?? "").PadRight(4, ' '));
            sb.Append((detail.Service_Provider_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.Service_Provider_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Service_Provider_ID_Qualifier_Alternate ?? "").PadRight(2, ' '));
            sb.Append((detail.Service_Provider_ID_Alternate ?? "").PadRight(15, ' '));
            sb.Append((detail.Service_Provider_Chain_Code ?? "").PadRight(7, ' '));
            sb.Append((detail.Pharmacy_Name ?? "").PadRight(70, ' '));
            sb.Append((detail.PH_Address_Line_1 ?? "").PadRight(40, ' '));
            sb.Append((detail.PH_Address_Line_2 ?? "").PadRight(40, ' '));
            sb.Append((detail.PH_City ?? "").PadRight(30, ' '));
            sb.Append((detail.PH_State ?? "").PadRight(2, ' '));
            sb.Append((detail.PH_Zip ?? "").PadRight(15, ' '));
            sb.Append((detail.Service_Provider_Country_Code1 ?? "").PadRight(3, ' '));
            sb.Append((detail.Service_Provider_Country_Code2 ?? "").PadRight(2, ' '));
            sb.Append((detail.PH_Telephone_Number ?? "").PadRight(10, ' '));
            sb.Append((detail.PH_Telephone_Number_Extension ?? "").PadRight(8, ' '));
            sb.Append((detail.Pharmacy_Dispenser_Type_Qualifier ?? "").PadRight(1, ' '));
            sb.Append((detail.Pharmacy_Dispenser_Type ?? "").PadRight(2, ' '));
            sb.Append((detail.Pharmacy_Class_Code_Qualifier ?? "").PadRight(1, ' '));
            sb.Append((detail.Pharmacy_Class_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.In_Network_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.In_Network_Reimbursement_ID ?? "").PadRight(10, ' '));
            sb.Append((detail.Prescriber_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.Prescriber_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Prescriber_ID_Qualifier_Alternate ?? "").PadRight(2, ' '));
            sb.Append((detail.Prescriber_ID_Alternate ?? "").PadRight(15, ' '));
            sb.Append((detail.Prescriber_Taxonomy ?? "").PadRight(10, ' '));
            sb.Append((detail.Prescriber_Certification_Status ?? "").PadRight(2, ' '));
            sb.Append((detail.PS_Last_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.PS_First_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.PS_Telephone_Number ?? "").PadRight(10, ' '));
            sb.Append((detail.PS_Telephone_Number_Extension ?? "").PadRight(8, ' '));
            sb.Append((detail.Primary_Care_Provider_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.Primary_Care_Provider_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.PC_Last_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.PC_First_Name ?? "").PadRight(35, ' '));
            sb.Append((detail.Record_Status_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Claim_Media_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.Processor_Payment_Clarification_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.Prescription_Service_Reference_Number_Qualifier ?? "").PadRight(1, ' '));
            sb.Append((detail.Prescription_Service_Reference_Number ?? "").PadRight(12, ' '));
            sb.Append((detail.Product_Service_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.Product_Service_ID ?? "").PadRight(19, ' '));
            sb.Append((detail.Date_Of_Service ?? "").PadRight(8, ' '));
            sb.Append((detail.Adjudication_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Adjudication_Time ?? "").PadRight(6, ' '));
            sb.Append((detail.Original_Claim_Received_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Claim_Sequence_Number ?? "").PadRight(5, ' '));
            sb.Append((detail.Billing_Cycle_End_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Communication_Type_Indicator ?? "").PadRight(2, ' '));
            sb.Append((detail.Place_Of_Service ?? "").PadRight(2, ' '));
            sb.Append((detail.Patient_Residence ?? "").PadRight(2, ' '));
            sb.Append((detail.Prescription_Origin_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Member_Submitted_Claim_Payment_Release_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Claim_Date_Received_Inthemail ?? "").PadRight(8, ' '));
            sb.Append((detail.Internal_Mail_Order_Prescription_Service_Reference_Number ?? "").PadRight(15, ' '));
            sb.Append((detail.Version_Number_Of_Claim ?? "").PadRight(2, ' '));
            sb.Append((detail.Check_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Payment_ID ?? "").PadRight(30, ' '));
            sb.Append((detail.Associated_Prescription_Service_Reference_Number ?? "").PadRight(12, ' '));
            sb.Append((detail.Associated_Prescription_Service_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Quantity_Dispensed ?? "").PadRight(10, ' '));
            sb.Append((detail.Fill_Number ?? "").PadRight(2, ' '));
            sb.Append((detail.Days_Supply ?? "").PadRight(3, ' '));
            sb.Append((detail.Date_Prescription_Written ?? "").PadRight(8, ' '));
            sb.Append((detail.Dispense_As_Written_Prodcut_Sellection_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Number_Of_Refills_Authorized ?? "").PadRight(2, ' '));
            sb.Append((detail.Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((detail.Level_Of_Service ?? "").PadRight(2, ' '));
            sb.Append((detail.Dispensing_Status ?? "").PadRight(1, ' '));
            sb.Append((detail.Quantity_Intended_Dispense ?? "").PadRight(10, ' '));
            sb.Append((detail.Quantity_Prescribed ?? "").PadRight(10, ' '));
            sb.Append((detail.Days_Supply_Intended_Dispense ?? "").PadRight(3, ' '));
            sb.Append((detail.Fill_Number_Calculated ?? "").PadRight(2, ' '));
            sb.Append((detail.Compound_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Compound_Type ?? "").PadRight(2, ' '));
            sb.Append((detail.Compound_Route_Of_Administration ?? "").PadRight(2, ' '));
            sb.Append((detail.Route_Of_Administration ?? "").PadRight(11, ' '));
            sb.Append((detail.Diagnosis_Code_Qualifier1 ?? "").PadRight(2, ' '));
            sb.Append((detail.Diagnosis_Code1 ?? "").PadRight(15, ' '));
            sb.Append((detail.Diagnosis_Code_Qualifier2 ?? "").PadRight(2, ' '));
            sb.Append((detail.Diagnosis_Code2 ?? "").PadRight(15, ' '));
            sb.Append((detail.Diagnosis_Code_Qualifier3 ?? "").PadRight(2, ' '));
            sb.Append((detail.Diagnosis_Code3 ?? "").PadRight(15, ' '));
            sb.Append((detail.Diagnosis_Code_Qualifier4 ?? "").PadRight(2, ' '));
            sb.Append((detail.Diagnosis_Code4 ?? "").PadRight(15, ' '));
            sb.Append((detail.Diagnosis_Code_Qualifier5 ?? "").PadRight(2, ' '));
            sb.Append((detail.Diagnosis_Code5 ?? "").PadRight(15, ' '));
            sb.Append((detail.Reason_For_Service_Code01 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code01 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code01 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort01 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code02 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code02 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code02 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort02 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code03 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code03 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code03 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort03 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code04 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code04 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_For_Service_Code04 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort04 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code05 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code05 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code05 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort05 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code06 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code06 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code06 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort06 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code07 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code07 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_Of_Service_Code07 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort07 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code08 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code08 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_For_Service_Code08 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort08 ?? "").PadRight(2, ' '));
            sb.Append((detail.Reason_For_Service_Code09 ?? "").PadRight(2, ' '));
            sb.Append((detail.Professional_Service_Code09 ?? "").PadRight(2, ' '));
            sb.Append((detail.Result_For_Service_Code09 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Level_Of_Effort09 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((detail.Reject_Override_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Reject_Code1 ?? "").PadRight(3, ' '));
            sb.Append((detail.Reject_Code2 ?? "").PadRight(3, ' '));
            sb.Append((detail.Reject_Code3 ?? "").PadRight(3, ' '));
            sb.Append((detail.Reject_Code4 ?? "").PadRight(3, ' '));
            sb.Append((detail.Reject_Code5 ?? "").PadRight(3, ' '));
            sb.Append((detail.Claim_ID ?? "").PadRight(30, ' '));
            sb.Append((detail.Date_Of_Injury ?? "").PadRight(8, ' '));
            sb.Append((detail.Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Product_Name ?? "").PadRight(30, ' '));
            sb.Append((detail.Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((detail.Product_Strength ?? "").PadRight(15, ' '));
            sb.Append((detail.Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append("".PadRight(8, ' '));
            sb.Append((detail.Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.Maintenance_Drug_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((detail.Prescription_Over_The_Counter_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Submission_Clarification_Code1 ?? "").PadRight(2, ' '));
            sb.Append((detail.Submission_Clarification_Code2 ?? "").PadRight(2, ' '));
            sb.Append((detail.Submission_Clarification_Code3 ?? "").PadRight(2, ' '));
            sb.Append((detail.FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((detail.Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((detail.Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((detail.Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((detail.Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((detail.Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((detail.Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((detail.Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Prescribed_Days_Supply ?? "").PadRight(3, ' '));
            sb.Append((detail.Therapeutic_Claim_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((detail.Therapeutic_Claim_Code1 ?? "").PadRight(17, ' '));
            sb.Append((detail.Therapeutic_Claim_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((detail.Therapeutic_Claim_Code2 ?? "").PadRight(17, ' '));
            sb.Append((detail.Therapeutic_Claim_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((detail.Therapeutic_Claim_Code3 ?? "").PadRight(17, ' '));
            sb.Append((detail.Therapeutic_Claim_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((detail.Therapeutic_Claim_Code4 ?? "").PadRight(17, ' '));
            sb.Append((detail.Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((detail.Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((detail.Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((detail.Formulary_File_ID ?? "").PadRight(15, ' '));
            sb.Append((detail.Formulary_Code_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.Ingradient_Cost_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Dispense_Fee_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Total_Amount_Paid_By_All_Sources ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Sales_Tax ?? "").PadRight(8, ' '));
            sb.Append((detail.Patient_Pay_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Of_Copay ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Of_Coinsurance ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Product_Sellection ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Applied_To_Periodic_Deductible ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Processor_Fee ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Provider_Network_Sellection ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Product_Selection_Brand_Drug ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Product_Selection_NonPreferred_Formulary ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Product_Selection_Brand_NonPreferred_Formulary ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Attributed_To_Coverage_Gap ?? "").PadRight(8, ' '));
            sb.Append((detail.MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((detail.Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.OutofPocket_Apply_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((detail.Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((detail.Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((detail.Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((detail.Gross_Amount_Due ?? "").PadRight(8, ' '));
            sb.Append((detail.MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((detail.Ingredient_Cost_Submitted ?? "").PadRight(8, ' '));
            sb.Append((detail.Usual_And_Customary_Charge ?? "").PadRight(8, ' '));
            sb.Append((detail.Flat_Sales_Tax_Amount_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Percentage_Sales_Tax_Amount_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Percentage_Sales_Tax_Rate_Paid ?? "").PadRight(7, ' '));
            sb.Append((detail.Percentage_Sales_Tax_Basis_Paid ?? "").PadRight(2, ' '));
            sb.Append((detail.Incentive_Amount_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Professional_Service_Fee_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.Other_Amount_Paid_Qualifier1 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Amount_Paid1 ?? "").PadRight(8, ' '));
            sb.Append((detail.Other_Amount_Paid_Qualifier2 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Amount_Paid2 ?? "").PadRight(8, ' '));
            sb.Append((detail.Other_Amount_Paid_Qualifier3 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Amount_Paid3 ?? "").PadRight(8, ' '));
            sb.Append((detail.Other_Payer_Amount_Recognized ?? "").PadRight(8, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier1 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount1 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier2 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount2 ?? "").PadRight(10, ' '));
            sb.Append((detail.Net_Amount_Due ?? "").PadRight(8, ' '));
            sb.Append((detail.Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((detail.Accumulated_Deductible_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Remaining_Deductible_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Remaining_Benefit_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Cost_Difference_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Excess_Copay_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Member_Submit_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Hold_Harmless_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Amount_Exceeding_Periodic_Benefit_Maximum ?? "").PadRight(8, ' '));
            sb.Append((detail.Basis_Of_Calculation_Dispensing_Fee ?? "").PadRight(2, ' '));
            sb.Append((detail.Basis_Of_Calculation_Copay ?? "").PadRight(2, ' '));
            sb.Append((detail.Basis_Of_Calculation_Flat_Sales_Tax ?? "").PadRight(2, ' '));
            sb.Append((detail.Basis_Of_Calculation_Percentage_Sales_Tax ?? "").PadRight(2, ' '));
            sb.Append((detail.Basis_Of_Calculation_Coinsurance ?? "").PadRight(2, ' '));
            sb.Append((detail.Tax_Excempt_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Medicare_Recovery_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Medicare_Recovery_Dispensing_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Patient_Spend_Down_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Health_Care_Reimbursement_Account_Amount_Applied ?? "").PadRight(8, ' '));
            sb.Append((detail.Health_Care_Reimbursement_Account_Amount_Remaining ?? "").PadRight(8, ' '));
            sb.Append((detail.Administrative_Fee_Effect_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Administrative_Fee_Amount ?? "").PadRight(4, ' '));
            sb.Append((detail.Invoiced_Amount ?? "").PadRight(11, ' '));
            sb.Append("".PadRight(10, ' '));
            sb.Append((detail.Spending_Account_Amount_Remaining ?? "").PadRight(8, ' '));
            sb.Append((detail.Health_Plan_Funded_Assistance_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Prior_Authorization_Type_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.Prior_Authorization_Number_Submitted ?? "").PadRight(11, ' '));
            sb.Append((detail.Prior_Authorization_Number_Assigned ?? "").PadRight(11, ' '));
            sb.Append((detail.Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((detail.Adjustment_Reason_Code ?? "").PadRight(3, ' '));
            sb.Append((detail.Adjustment_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.Transaction_ID_Cross_Reference ?? "").PadRight(30, ' '));
            sb.Append((detail.COB_Carrier_Submit_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Eligibility_COB_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.COB_Primary_Claim_Type ?? "").PadRight(1, ' '));
            sb.Append((detail.COB_Primary_Payer_ID ?? "").PadRight(10, ' '));
            sb.Append("".PadRight(8, ' '));
            sb.Append((detail.COB_Primary_Payer_Amount_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Primary_Payer_Deductible ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Primary_Payer_Coinsurance ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Primary_Payer_Copay ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Secondary_Payer_ID ?? "").PadRight(10, ' '));
            sb.Append("".PadRight(8, ' '));
            sb.Append((detail.COB_Secondary_Payer_Amount_Paid ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Secondary_Payer_Deductible ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Secondary_Payer_Coinsurance ?? "").PadRight(8, ' '));
            sb.Append((detail.COB_Secondary_Payer_Copay ?? "").PadRight(8, ' '));
            sb.Append((detail.Transaction_ID ?? "").PadRight(30, ' '));
            sb.Append((detail.Authorization_Number ?? "").PadRight(20, ' '));
            sb.Append((detail.Client_Specific_Data ?? "").PadRight(50, ' '));
            sb.Append((detail.Processor_Specific_Data ?? "").PadRight(50, ' '));
            sb.Append((detail.CMS_PartD_Defined_Qualified_Facility ?? "").PadRight(1, ' '));
            sb.Append((detail.Benefit_Stage_Qualifier1 ?? "").PadRight(2, ' '));
            sb.Append((detail.Benefit_Stage_Amount1 ?? "").PadRight(8, ' '));
            sb.Append((detail.Benefit_Stage_Qualifier2 ?? "").PadRight(2, ' '));
            sb.Append((detail.Benefit_Stage_Amount2 ?? "").PadRight(8, ' '));
            sb.Append((detail.Benefit_Stage_Qualifier3 ?? "").PadRight(2, ' '));
            sb.Append((detail.Benefit_Stage_Amount3 ?? "").PadRight(8, ' '));
            sb.Append((detail.Benefit_Stage_Qualifier4 ?? "").PadRight(2, ' '));
            sb.Append((detail.Benefit_Stage_Amount4 ?? "").PadRight(8, ' '));
            sb.Append((detail.Invoiced_Date ?? "").PadRight(8, ' '));
            sb.Append((detail.Outofpocket_Remaining_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.Card_Holder_ID_Alternate ?? "").PadRight(20, ' '));
            sb.Append((detail.Number_Of_Generic_Manufacturers ?? "").PadRight(3, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier1 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID1 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier2 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID2 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier3 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID3 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier4 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID4 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier5 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID5 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier6 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID6 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier7 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID7 ?? "").PadRight(19, ' '));
            sb.Append((detail.DUR_Coagent_ID_Qualifier8 ?? "").PadRight(2, ' '));
            sb.Append((detail.DUR_Coagent_ID8 ?? "").PadRight(19, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier01 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount01 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier02 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount02 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier03 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount03 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier04 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount04 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier05 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount05 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier06 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount06 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier07 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount07 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier08 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount08 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier09 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount09 ?? "").PadRight(10, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount_Qualifier10 ?? "").PadRight(2, ' '));
            sb.Append((detail.Other_Payer_Patient_Responsibility_Amount10 ?? "").PadRight(10, ' '));
            sb.Append((detail.Specialty_Claim_Indicator ?? "").PadRight(1, ' '));
            sb.Append((detail.Member_Submitted_Claim_Reject_Code1 ?? "").PadRight(3, ' '));
            sb.Append((detail.Member_Submitted_Claim_Reject_Code2 ?? "").PadRight(3, ' '));
            sb.Append((detail.Member_Submitted_Claim_Reject_Code3 ?? "").PadRight(3, ' '));
            sb.Append((detail.Member_Submitted_Claim_Reject_Code4 ?? "").PadRight(3, ' '));
            sb.Append((detail.Member_Submitted_Claim_Reject_Code5 ?? "").PadRight(3, ' '));
            sb.Append((detail.Copay_Waiver_Amount ?? "").PadRight(8, ' '));
            sb.Append((detail.CMS_PartD_Contract_ID ?? "").PadRight(5, ' '));
            sb.Append((detail.Medicare_PartD_Plan_Benefit_Package ?? "").PadRight(3, ' '));
            sb.Append((detail.Medicare_Drug_Coverage_Code ?? "").PadRight(2, ' '));
            sb.Append("".PadRight(405,' '));
            return sb.ToString();
        }
        private string Pah42Cd1(HisCompound1 cd1) 
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("CD");
            sb.Append((cd1.Prescription_Reference_Number_Qualifier ?? "").PadRight(1, ' '));
            sb.Append((cd1.Prescription_Reference_Number ?? "").PadRight(12, ' '));
            sb.Append((cd1.Compound_Ingredient_Component_Count ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_Compound_Product_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_Compound_Product_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.First_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.First_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.First_Compound_Ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.First_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.First_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.First_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.First_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.First_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.First_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.First_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.First_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.First_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.First_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.First_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.First_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.First_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.First_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Second_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Second_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Second_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Second_Compound_Ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Second_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Second_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Second_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Second_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Second_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_Proceddor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Second_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Second_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Second_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Second_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Second_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Second_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Second_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Second_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Second_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Third_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Third_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Third_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Third_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Third_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Third_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Third_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Third_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Third_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Third_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Third_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Third_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Third_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Third_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Third_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Third_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Third_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Third_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fourth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Fourth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Fourth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fourth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Fourth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Fourth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Fourth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Fourth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fourth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Fourth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fourth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fourth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fourth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fourth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fourth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fourth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fourth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fourth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fifth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Fifth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Fifth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fifth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Fifth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Fifth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Fifth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Fifth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Fifth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Fifth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Fifth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Fifth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fifth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fifth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fifth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fifth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Fifth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Fifth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Sixth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Sixth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Sixth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Sixth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Sixth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Sixth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Sixth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Sixth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Sixth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Sixth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Sixth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Sixth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Sixth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Sixth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Sixth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Sixth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Sixth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Sixth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Seventh_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Seventh_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Seventh_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Seventh_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Seventh_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Seventh_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Seventh_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Seventh_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Seventh_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Seventh_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Seventh_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Seventh_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Seventh_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Seventh_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Seventh_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Seventh_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Seventh_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Seventh_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd1.Eighth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Eighth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd1.Eighth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd1.Eighth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Eighth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd1.Eighth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd1.Eighth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd1.Eighth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd1.Eighth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd1.Eighth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd1.Eighth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd1.Eighth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Eighth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Eighth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Eighth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Eighth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd1.Eighth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd1.Eighth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append("".PadRight(907, ' '));
            return sb.ToString();
        }
        private string Pah42Cd2(HisCompound2 cd2) 
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("CE");
            sb.Append((cd2.Prescription_Reference_Number_Qualifier ?? "").PadRight(1, ' '));
            sb.Append((cd2.Prescription_Reference_Number ?? "").PadRight(12, ' '));
            sb.Append((cd2.Compound_Ingredient_Component_Count ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Ninth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Ninth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Ninth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Ninth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Ninth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Ninth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Ninth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Ninth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Ninth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Ninth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Ninth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Ninth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Ninth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Ninth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Ninth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Ninth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Ninth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Tenth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Tenth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Tenth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Tenth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Tenth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Tenth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Tenth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Tenth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Tenth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Tenth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Tenth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Tenth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Tenth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Tenth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Tenth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Tenth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Tenth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Tenth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Eleventh_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Eleventh_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Eleventh_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Eleventh_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Eleventh_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Eleventh_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Eleventh_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Eleventh_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Eleventh_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Eleventh_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Eleventh_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Eleventh_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Eleventh_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Eleventh_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Eleventh_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Eleventh_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Eleventh_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Eleventh_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Twelfth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Twelfth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Twelfth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Twelfth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Twelfth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Twelfth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Twelfth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Twelfth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Twelfth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Twelfth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Twelfth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Twelfth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Twelfth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Twelfth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Twelfth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Twelfth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Twelfth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Twelfth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Thirteenth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Thirteenth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Thirteenth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Thirteenth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Thirteenth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Thirteenth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Thirteenth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Thirteenth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Thirteenth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Thirteenth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Thirteenth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Thirteenth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Thirteenth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Thirteenth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Thirteenth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Thirteenth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Thirteenth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Thirteenth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fourteenth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Fourteenth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Fourteenth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fourteenth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Fourteenth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Fourteenth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Fourteenth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Fourteenth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fourteenth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Fourteenth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fourteenth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fourteenth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fourteenth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fourteenth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fourteenth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fourteenth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fourteenth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fourteenth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fifteenth_Compound_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_Compound_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Fifteenth_Compound_Ingredient_Quantity ?? "").PadRight(14, ' '));
            sb.Append((cd2.Fifteenth_Compound_Ingredient_Drug_Cost ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fifteenth_Compound_ingredient_Basis_Of_Cost_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_Client_Formulary_Flag ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Product_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Fifteenth_Generic_Name ?? "").PadRight(30, ' '));
            sb.Append((cd2.Fifteenth_Product_Strength ?? "").PadRight(10, ' '));
            sb.Append((cd2.Fifteenth_Dosage_Form_Code ?? "").PadRight(4, ' '));
            sb.Append((cd2.Fifteenth_Database_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Drug_Type ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Formulary_Status ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Drug_Category_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Federal_DEA_Schedule ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_FDA_Drug_Efficacy_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Product_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Product_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Product_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Product_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Product_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Product_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Federal_Upper_Limit_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code_Qualifier1 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code1 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code_Qualifier2 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code2 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code_Qualifier3 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code3 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code_Qualifier4 ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Class_Code4 ?? "").PadRight(17, ' '));
            sb.Append((cd2.Fifteenth_Special_Packaging_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Unit_Of_Measure ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_Processor_Defined_Prior_Authorization_Reason_Code ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_MAC_Reduced_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Client_Pricing_Basis_Of_Cost ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_DUR_Coagent_ID_Qualifier ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_DUR_Coagent_ID ?? "").PadRight(19, ' '));
            sb.Append((cd2.Fifteenth_Generic_Indicator ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Plan_Cutback_Reason_Code ?? "").PadRight(1, ' '));
            sb.Append((cd2.Fifteenth_Therapeutic_Chapter ?? "").PadRight(8, ' '));
            sb.Append((cd2.Fifteenth_Average_Cost_Per_Quantity_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fifteenth_Average_Generic_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fifteenth_Average_Wholesale_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fifteenth_Federal_Upper_Limit_Unit_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fifteenth_MAC_Price ?? "").PadRight(9, ' '));
            sb.Append((cd2.Fifteenth_Basis_Of_Reimbursement_Determination ?? "").PadRight(2, ' '));
            sb.Append((cd2.Fifteenth_Patient_Formulary_Rebate_Amount ?? "").PadRight(8, ' '));
            sb.Append("".PadRight(1252, ' '));
            return sb.ToString();
        }
    }
}
